##
##   Copyright (c) 2020-2022 Intel Corporation.
##
##   Licensed under the Apache License, Version 2.0 (the "License");
##   you may not use this file except in compliance with the License.
##   You may obtain a copy of the License at
##
##       http://www.apache.org/licenses/LICENSE-2.0
##
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.
##
---
intel_qat_dp_git_url: "https://github.com/intel/intel-device-plugins-for-kubernetes.git"
intel_qat_dp_git_ref: "v0.23.0"
intel_qat_dp_version: "0.23.0"
intel_qat_dp_dir: "{{ (project_root_dir, 'intel-qat-dp') | path_join }}"

qat_dp_namespace: "kube-system"
qat_dp_dpdk_drivers: "vfio-pci"
qat_dp_kernel_drivers:
  - dh895xccvf
  - c4xxxvf
  - c3xxxvf
  - 4xxxvf
  - c6xxvf
  - d15xxvf
qat_dp_apparmor: "true"
qat_dp_apparmor_profile: "unconfined"
