##
##   Copyright (c) 2020-2022 Intel Corporation.
##
##   Licensed under the Apache License, Version 2.0 (the "License");
##   you may not use this file except in compliance with the License.
##   You may obtain a copy of the License at
##
##       http://www.apache.org/licenses/LICENSE-2.0
##
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.
##
---
- name: uninstall MinIO
  block:
    - name: set iteration number
      set_fact:
        num: 1
        req_num: "{{ hostvars[inventory_hostname]['minio_pv'] |length }}"

    - name: umount volumes
      command: >-
        umount --lazy "{{ item.mountPath }}"
      loop: "{{ hostvars[inventory_hostname]['minio_pv'] }}"
      when:
        - hostvars[inventory_hostname]['minio_pv'] is defined and hostvars[inventory_hostname]['minio_pv']|length > 0
      changed_when: false
      failed_when: false

    - name: remove paritions for nvme deploy
      parted:
        device: "{{ item.device }}"
        number: 1
        state: absent
      loop: "{{ hostvars[inventory_hostname]['minio_pv'] }}"
      when:
        - hostvars[inventory_hostname]['minio_pv'] is defined and hostvars[inventory_hostname]['minio_pv']|length > 0
      changed_when: false
      failed_when: false

    - name: list loop devices
      shell: >-
        set -o pipefail && losetup -l |grep diskimage |awk -F " " '{ print $6,$1}' |sort |awk -F " " '{ print $2}'
      args:
        executable: /bin/bash
      register: loopdevice_output
      changed_when: false
      failed_when: false

    - name: remove loop devices for test mode deploy (block device)
      command: >-
        losetup -d "{{ item }}"
      loop: "{{ loopdevice_output.stdout_lines }}"
      changed_when: false
      failed_when: false

    - name: remove mount points
      file:
        path: "{{ item.mountPath }}"
        state: absent
      loop: "{{ hostvars[inventory_hostname]['minio_pv'] }}"
      when:
        - hostvars[inventory_hostname]['minio_pv'] is defined and hostvars[inventory_hostname]['minio_pv']|length > 0
      changed_when: false
      failed_when: false

    - name: remove block device files (diskimages)
      file:
        path: "{{ ('/tmp', 'diskimage' ~ ansible_loop.index) | path_join }}"
        state: absent
      loop: "{{ range(num, req_num|int + 1) | list }}"
      loop_control:
        extended: yes
      changed_when: false
      failed_when: false
  when:
    - inventory_hostname in groups['kube_node']
    - minio_enabled | default(false) | bool

- name: remove mount points from /etc/fstab
  shell: >-
    set -o pipefail && cat /etc/fstab | sed "{{ item.mountPath | replace('/', '\\/') }}"/d | tee /etc/fstab
  args:
    executable: /bin/bash
  loop: "{{ hostvars[inventory_hostname]['minio_pv'] }}"
  when:
    - hostvars[inventory_hostname]['minio_pv'] is defined and hostvars[inventory_hostname]['minio_pv']|length > 0
    - inventory_hostname in groups['kube_node']
  changed_when: false
  failed_when: false
