##
##   Copyright (c) 2020-2022 Intel Corporation.
##
##   Licensed under the Apache License, Version 2.0 (the "License");
##   you may not use this file except in compliance with the License.
##   You may obtain a copy of the License at
##
##       http://www.apache.org/licenses/LICENSE-2.0
##
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.
##
---
- name: create file block devices
  command: >-
    dd
    if=/dev/zero of=/tmp/diskimage{{ ansible_loop.index }}
    bs=1M
    count=
    {%- if hostvars[inventory_hostname]['minio_pv'][ansible_loop.index0].capacity.endswith('GiB') -%}
    "{{ hostvars[inventory_hostname]['minio_pv'][ansible_loop.index0].capacity[:-3] |int * 1024 }}"
    {%- elif hostvars[inventory_hostname]['minio_pv'][ansible_loop.index0].capacity.endswith('TiB') -%}
    "{{ hostvars[inventory_hostname]['minio_pv'][ansible_loop.index0].capacity[:-3]|int * 1024 * 1024 }}"
    {%- else -%}
    "{{ hostvars[inventory_hostname]['minio_pv'][ansible_loop.index0].capacity }}"
    {%- endif -%}
  changed_when: true

- name: create mount point for the file block devices
  file:
    path: "{{ hostvars[inventory_hostname]['minio_pv'][ansible_loop.index0].mountPath }}"
    state: directory
    mode: 0755
