- hosts: localhost
  become: true
  become_user: root
  tasks:
  - name: check the uptime
    tags: always
    command: uptime
  pre_tasks:
  - name: create the systemd unit to start the second playbook after reboot
    tags: always
    copy:
      src: files/filip.service
      dest: /etc/systemd/system
  - name: enable the unit to execute at reboot
    tags: always
    command: sudo systemctl enable filip.service
  - name: reload the units
    tags: always
    command: sudo systemctl daemon-reload
- hosts: localhost
  become: true
  become_user: root
  tasks:
  - name: check the date
    tags: always
    command: date
  pre_tasks: []
- hosts: localhost
  become: true
  become_user: root
  tasks:
  - name: check the uptime before reboot
    tags: always
    command: uptime
  - block:
    - name: increment the reboot counter
      lineinfile:
        dest: inventory
        'regexp:': rebootCounter
        line: rebootCounter = 1
    - name: reboot the local host
      command: sudo reboot
    when: rebootCounter == 0
  - name: check the control host uptime after reboot
    tags: always
    register: uptimeoutput
    command: uptime
  - local_action: copy content={{ uptimeoutput }} dest=~/uptime.txt
  - name: delete the systemd unit
    tags: always
    file:
      state: absent
      path: /etc/systemd/system/filip.service
  - name: reload the units
    tags: always
    command: sudo systemctl daemon-reload
  pre_tasks: []
