##
##   Copyright (c) 2020-2022 Intel Corporation.
##
##   Licensed under the Apache License, Version 2.0 (the "License");
##   you may not use this file except in compliance with the License.
##   You may obtain a copy of the License at
##
##       http://www.apache.org/licenses/LICENSE-2.0
##
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.
##
---
# This var is not intended to be customized by user
# Define respective field in the group_vars/all.yml instead
tca_defaults:
  enabled: false
  apphsm_hostmane: "{{ hostvars[groups['kube_node'][0]]['ansible_default_ipv4']['address'] }}"
  apphsm_port: 5000
  client_mtls_secret_name: "generic-apphsm-client-tls"
  client_mtls_secret_namespace: "kmra"
  build_image_locally: false
  namespace: tca
