---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: intel-ethernet-operator
spec:
  privileged: true
  hostPID: true
  hostNetwork: true
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - '*'
  allowedUnsafeSysctls:
  - '*'
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'
