---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: collectd
rules:
  - apiGroups: ["authentication.k8s.io"]
    resources:
      - tokenreviews
    verbs: ["create"]
  - apiGroups: ["authorization.k8s.io"]
    resources:
      - subjectaccessreviews
    verbs: ["create"]
{% if psp_enabled %}
  - apiGroups: ['policy']
    resources: ['podsecuritypolicies']
    verbs:     ['use']
    resourceNames:
      - collectd
{% endif %}
