---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: collectd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: collectd
subjects:
  - kind: ServiceAccount
    name: collectd
    namespace: "{{ collectd_namespace }}"
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: system:serviceaccounts
