---
apiVersion: v1
kind: Service
metadata:
  name: collectd-service
  labels:
    app: collectd-service
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: collectd
  ports:
  - name: https
    port: 9104
    targetPort: https
    protocol: TCP
