##
##   Copyright (c) 2020-2022 Intel Corporation.
##
##   Licensed under the Apache License, Version 2.0 (the "License");
##   you may not use this file except in compliance with the License.
##   You may obtain a copy of the License at
##
##       http://www.apache.org/licenses/LICENSE-2.0
##
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.
##
---
intel_gpu_dp_git_url: "https://github.com/intel/intel-device-plugins-for-kubernetes.git"
intel_gpu_dp_git_ref: "v0.23.0"
intel_gpu_dp_version: "0.23.0"
intel_gpu_dp_dir: "{{ (project_root_dir, 'intel-gpu-dp') | path_join }}"

gpu_dp_shared_devices: 10
gpu_dp_verbosity: 4
gpu_dp_monitor_resources: false
gpu_dp_fractional_manager: false
gpu_dp_build_image_locally: false
