---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "telegraf.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "telegraf.labels" . | nindent 4 }}
spec:
  commonName: "{{ include "telegraf.fullname" . }}.{{ .Release.Namespace }}.svc"
  dnsNames:
  - "{{ include "telegraf.fullname" . }}.{{ .Release.Namespace }}.svc"
  - "{{ include "telegraf.fullname" . }}.{{ .Release.Namespace }}"
  - "{{ include "telegraf.fullname" . }}"
  isCA: true
  issuerRef:
    kind: Issuer
    name: {{ include "telegraf.fullname" . }}-issuer
  secretName: {{ include "telegraf.fullname" . }}-tls
  usages:
  - digital signature
  - key encipherment
  - server auth

