---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "telegraf.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "telegraf.labels" . | nindent 4 }}
data:
  telegraf.conf: {{ toYaml .Values.telegraf.config | indent 2 }}

