---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "telegraf.fullname" . }}
  labels:
    {{- include "telegraf.labels" . | nindent 4 }}
spec:
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - '*'
  allowedUnsafeSysctls:
  - '*'
  fsGroup:
    rule: RunAsAny
  hostNetwork: true
  hostPorts:
  - max: {{ .Values.prometheusMetricsEndpointPort }}
    min: {{ .Values.prometheusMetricsEndpointPort }}
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - "configMap"
    - "downwardAPI"
    - "emptyDir"
    - "persistentVolumeClaim"
    - "secret"
    - "projected"
    - "hostPath"
