apiVersion: v1
kind: Service
metadata:
  name: {{ include "telegraf.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "telegraf.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.prometheusMetricsEndpointPort }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "telegraf.selectorLabels" . | nindent 4 }}
