##
##   Copyright (c) 2020-2022 Intel Corporation.
##
##   Licensed under the Apache License, Version 2.0 (the "License");
##   you may not use this file except in compliance with the License.
##   You may obtain a copy of the License at
##
##       http://www.apache.org/licenses/LICENSE-2.0
##
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.
##
---
- name: install dependencies
  include_role:
    name: install_dependencies

- name: clone SRIOV Network Device Plugin repository
  git:
    repo: "{{ sriov_net_dp_git_url }}"
    version: "{{ sriov_net_dp_tag }}"
    dest: "{{ sriov_net_dp_dir }}"
    force: yes
  when:
    - inventory_hostname == groups['kube_node'][0]
    - sriov_net_dp_build_image_locally

- name: build SRIOV Network Device Plugin image behind proxy
  make:
    target: image
    chdir: "{{ sriov_net_dp_dir }}"
    params:
      HTTP_PROXY: "{{ http_proxy }}"
      HTTPS_PROXY: "{{ https_proxy }}"
  when:
    - inventory_hostname == groups['kube_node'][0]
    - sriov_net_dp_build_image_locally
    - http_proxy is defined
    - https_proxy is defined
    - container_runtime == "docker"
  register: sriov_dp_image_build
  retries: 5
  until: sriov_dp_image_build is success

- name: build SRIOV Network Device Plugin image
  make:
    target: image
    chdir: "{{ sriov_net_dp_dir }}"
  when:
    - inventory_hostname == groups['kube_node'][0]
    - sriov_net_dp_build_image_locally
    - http_proxy is not defined
    - https_proxy is not defined
    - container_runtime == "docker"
  register: sriov_dp_image_build
  retries: 5
  until: sriov_dp_image_build is success

- name: tag SRIOV Network Device Plugin image
  command: docker tag {{ sriov_net_dp_image }}:latest {{ registry_local_address }}/sriov-device-plugin:{{ sriov_net_dp_tag }}
  when:
    - inventory_hostname == groups['kube_node'][0]
    - sriov_net_dp_build_image_locally
    - container_runtime == "docker"

- name: push SRIOV Network Device Plugin image to local registry
  command: docker push {{ registry_local_address }}/sriov-device-plugin:{{ sriov_net_dp_tag }}
  when:
    - inventory_hostname == groups['kube_node'][0]
    - sriov_net_dp_build_image_locally
    - container_runtime == "docker"

- name: build and tag SRIOV Network Device Plugin image behind proxy
  shell: >-
    podman build -t {{ registry_local_address }}/{{ item.name }}:{{ sriov_net_dp_tag }}
    --build-arg=http_proxy=${http_proxy}
    --build-arg=https_proxy=${https_proxy}
    -f {{ item.file }} .
  args:
    chdir: "{{ sriov_net_dp_dir }}"
  changed_when: true
  with_items:
    - { file: images/Dockerfile, name: sriov-device-plugin }
  register: sriov_dp_image_build
  retries: 5
  until: sriov_dp_image_build is success
  when:
    - inventory_hostname == groups['kube_node'][0]
    - sriov_net_dp_build_image_locally
    - '"docker" not in container_runtime'
    - http_proxy is defined
    - https_proxy is defined

- name: build and tag SRIOV Network Device Plugin image
  command: podman build -t {{ registry_local_address }}/{{ item.name }}:{{ sriov_net_dp_tag }} -f {{ item.file }} .
  args:
    chdir: "{{ sriov_net_dp_dir }}"
  changed_when: true
  with_items:
    - { file: images/Dockerfile, name: sriov-device-plugin }
  register: sriov_dp_image_build
  retries: 5
  until: sriov_dp_image_build is success
  when:
    - inventory_hostname == groups['kube_node'][0]
    - sriov_net_dp_build_image_locally
    - '"docker" not in container_runtime'
    - http_proxy is not defined
    - https_proxy is not defined

- name: push SRIOV Network Device Plugin image to local registry
  command: podman push {{ registry_local_address }}/sriov-device-plugin:{{ sriov_net_dp_tag }}
  changed_when: true
  when:
    - inventory_hostname == groups['kube_node'][0]
    - sriov_net_dp_build_image_locally
    - '"docker" not in container_runtime'

- name: create Helm charts directory if needed
  file:
    path: "{{ (project_root_dir, 'charts') | path_join }}"
    state: directory
    mode: 0755
  when:
    - inventory_hostname == groups['kube_control_plane'][0]

- name: copy SRIOV Network Device Plugin Helm chart to the controller node
  copy:
    src: "{{ (role_path, 'charts', 'sriov-net-dp') | path_join }}"
    dest: "{{ (project_root_dir, 'charts') | path_join }}"
    mode: 0755
  when:
    - inventory_hostname == groups['kube_control_plane'][0]

- name: set values for SRIOV Network Device Plugin Helm chart values for locally built and stored image
  set_fact:
    sriov_net_dp_image: "{{ registry_local_address }}/sriov-device-plugin"
  when:
    - sriov_net_dp_build_image_locally
    - inventory_hostname == groups['kube_control_plane'][0]

- name: populate SRIOV Network Device Plugin Helm chart values template and push to controller node
  template:
    src: "helm_values.yml.j2"
    dest: "{{ (project_root_dir, 'charts', 'sriov-net-dp-values.yml') | path_join }}"
    force: yes
    mode: preserve
  when:
    - inventory_hostname == groups['kube_control_plane'][0]

- name: install SRIOV Network Device Plugin helm chart
  command: >-
    helm upgrade -i sriov-net-dp
    -f {{ (project_root_dir, 'charts', 'sriov-net-dp-values.yml') | path_join }}
    {{ (project_root_dir, 'charts', 'sriov-net-dp') | path_join }}
  when:
    - inventory_hostname == groups['kube_control_plane'][0]
