# SPDX-License-Identifier: Apache-2.0
# Copyright(c) Copyright 2018 CoreOS, Inc
#
# Modifications copyright (C) 2020 Intel Corporation
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 1.3.1
