# SPDX-License-Identifier: Apache-2.0
# Copyright(c) Copyright 2018 CoreOS, Inc
#
# Modifications copyright (C) 2020 Intel Corporation
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-prometheus-grafana
  namespace: monitoring
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 8.3.4
spec:
  storageClassName: kube-prometheus
  selector:
    matchLabels:
      name: kube-prometheus-grafana
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
