# SPDX-License-Identifier: Apache-2.0
# Copyright(c) Copyright 2018 CoreOS, Inc
#
# Modifications copyright (C) 2020 Intel Corporation
apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: k8s
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 2.35.0
  name: prometheus-k8s
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - name: grafana-https
    port: 3000
    nodePort: 30000
    targetPort: grafana-https
  selector:
    app: prometheus
    prometheus: k8s
  sessionAffinity: ClientIP
