##
##   Copyright (c) 2020-2022 Intel Corporation.
##
##   Licensed under the Apache License, Version 2.0 (the "License");
##   you may not use this file except in compliance with the License.
##   You may obtain a copy of the License at
##
##       http://www.apache.org/licenses/LICENSE-2.0
##
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.
##
---
crio_versioned_pkg:
  "1.23":
    - "cri-o=1.23*"
    - cri-o-runc
  "1.22":
    - "cri-o=1.22*"
    - cri-o-runc
  "1.21":
    - "cri-o=1.21*"
    - cri-o-runc

crio_packages: "{{ crio_versioned_pkg[crio_version] }}"

# The crio_runtimes variable defines a list of OCI compatible runtimes.
crio_runtimes:
  - name: runc
    path: /usr/sbin/runc
    type: oci
    root: /run/runc
