apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: intel-sgx-plugin
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
    - intel-sgx-plugin
