##
##   Copyright (c) 2020-2022 Intel Corporation.
##
##   Licensed under the Apache License, Version 2.0 (the "License");
##   you may not use this file except in compliance with the License.
##   You may obtain a copy of the License at
##
##       http://www.apache.org/licenses/LICENSE-2.0
##
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.
##
---
- block:
  - name: starting download of file
    debug:
      msg: "{{ crictl.url }}"

  - name: create dest directory on node
    file:
      path: "{{ crictl.dest | dirname }}"
      owner: "{{ crictl.owner }}"
      mode: 0755
      state: directory
      recurse: yes

  - name: download item
    get_url:
      url: "{{ crictl.url }}"
      dest: "{{ crictl.dest }}"
      owner: "{{ crictl.owner }}"
      mode: "{{ crictl.mode }}"
      checksum: "{{ 'sha256:' + crictl.sha256 }}"
    delegate_to: "{{ inventory_hostname }}"
    register: get_url_result
    until: "'OK' in get_url_result.msg or 'file already exists' in get_url_result.msg"
    retries: 4
    delay: 5
    no_log: true

  - name: unpack archive
    unarchive:
      src: "{{ crictl.dest }}"
      dest: "{{ crictl.dest | dirname }}"
      owner: "{{ crictl.owner }}"
      mode: "{{ crictl.mode }}"
      copy: no

- name: install crictl config
  template:
    src: crictl.yml.j2
    dest: /etc/crictl.yaml
    owner: root
    mode: 0644

- name: copy crictl binary from download dir
  copy:
    src: "{{ local_release_dir }}/crictl"
    dest: "{{ bin_dir }}/crictl"
    mode: 0755
    remote_src: true
  notify:
    - get crictl completion
    - install crictl completion

- name: Set fact crictl_installed
  set_fact:
    crictl_installed: true
