kind: Configuration
apiVersion: eventratelimit.admission.k8s.io/v1alpha1
limits:
- type: Server
  qps: 10
  burst: 50
- type: Namespace
  qps: 50
  burst: 100
- type: User
  qps: 10
  burst: 50
- type: SourceAndObject
  qps: 10
  burst: 50
