##
##   Copyright (c) 2020-2022 Intel Corporation.
##
##   Licensed under the Apache License, Version 2.0 (the "License");
##   you may not use this file except in compliance with the License.
##   You may obtain a copy of the License at
##
##       http://www.apache.org/licenses/LICENSE-2.0
##
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.
##
---
- name: assert that hugepages are enabled
  assert:
    that: hugepages_enabled | default(false)
    fail_msg: "Hugepages are disabled. Please configure hugepages in the host vars or disable OVS-DPDK installation."

- name: clone OVS git repository
  git:
    repo: '{{ ovs_repo }}'
    dest: '{{ ovs_dir }}'
    version: '{{ ovs_version | default("master") }}'
    force: yes
  register: ovs_changed

- name: check whether bootstrap is required
  stat: path={{ ovs_dir }}/configure
  register: ovs_config_status

- name: bootstrap OVS
# noqa 503 - more than one condition, can't be a handler
  command: ./boot.sh
  args:
    chdir: "{{ ovs_dir }}"
  when: not ovs_config_status.stat.exists or (ovs_rebuild is defined) or ovs_changed.changed

- name: Check if OVS Makefile exists
  stat: path={{ ovs_dir }}/Makefile
  register: ovs_makefile_status

- name: Set dpdk binding type for DPDK >= 20.08
  set_fact:
    dpdk_build: "static"
  when: dpdk_version is version("20.08", ">=")

- name: install dpdk-devel to prepare OVS-DPDK build in RHEL / CentOS >= 8.2
  dnf:
    name: dpdk-devel
  when: ansible_os_family == "RedHat" and ansible_distribution_version >= '8.2'

- name: update the dynamic linker cache in RHEL / CentOS >= 8.2
  command: "ldconfig"
  when: ansible_os_family == "RedHat" and ansible_distribution_version >= '8.2'
  changed_when: true

- name: prepare OVS-DPDK build in RHEL / CentOS >= 8.2
  command: ./configure --with-dpdk=yes CFLAGS="-g -O2 -Wno-cast-align"
  args:
    chdir: "{{ ovs_dir }}"
  environment:
    PKG_CONFIG_PATH: "/usr/local/lib64/pkgconfig:/usr/share/pkgconfig:/usr/lib64/pkgconfig"
  when:
    - ansible_os_family == "RedHat" and ansible_distribution_version >= '8.2'
    - not ovs_makefile_status.stat.exists or (ovs_rebuild is defined) or ovs_changed.changed

- name: prepare OVS-DPDK build
# noqa 503 - more than one condition, can't be a handler
  command: ./configure --with-dpdk={{ dpdk_build }} CFLAGS="-g -O2 -Wno-cast-align"
  args:
    chdir: "{{ ovs_dir }}"
  environment:
    PKG_CONFIG_PATH: "/usr/local/lib64/pkgconfig:/usr/share/pkgconfig:/usr/lib64/pkgconfig"
  when:
    - ansible_distribution == 'Ubuntu'
    - not ovs_makefile_status.stat.exists or (ovs_rebuild is defined) or ovs_changed.changed

- name: check if OVS distribution files exists
  stat: path={{ ovs_dir }}/distfiles
  register: ovs_distfiles_status

- name: build OVS-DPDK
# noqa 503 - more than one condition, can't be a handler
  make:
    chdir: "{{ ovs_dir }}"
    params:
      CFLAGS: '-O3 -march=native'
  when: not ovs_distfiles_status.stat.exists or (ovs_rebuild is defined) or ovs_changed.changed

- name: Check if OVS tools are installed
  stat: path=/usr/local/bin/ovsdb-tool
  register: ovs_tools_status

- name: install OVS-DPDK
# noqa 503 - more than one condition, can't be a handler
  make:
    target: install
    chdir: "{{ ovs_dir }}"
  when: not ovs_tools_status.stat.exists or (ovs_rebuild is defined) or ovs_changed.changed

- name: create OVS folders
  file: path={{ item }} state=directory mode=0755
  with_items:
    - /usr/local/etc/openvswitch
    - /usr/local/var/run/openvswitch

- name: clear database configuration if required
# noqa 503 - more than one condition, can't be a handler
  file:
    path: /usr/local/etc/openvswitch/conf.db
    state: absent
  when: ovs_rebuild is defined or ovs_changed.changed

- name: check if database configuration exists
  stat: path=/usr/local/etc/openvswitch/conf.db
  register: ovs_dbconfig_status

- name: create database configuration
  command: '/usr/local/bin/ovsdb-tool create /usr/local/etc/openvswitch/conf.db /usr/local/share/openvswitch/vswitch.ovsschema'
  when: not ovs_dbconfig_status.stat.exists

- name: start OVS database server
  command: '/usr/local/share/openvswitch/scripts/ovs-ctl --no-ovs-vswitchd start'
  environment:
    OVS_RUNDIR: /usr/local/var/run/openvswitch
  changed_when: true

- name: set OVS dpdk-socket-mem
  command: '/usr/local/bin/ovs-vsctl --no-wait set Open_vSwitch . other_config:dpdk-socket-mem="{{ ovs_dpdk_socket_mem  }}"'
  changed_when: true

- name: set OVS dpdk-init
  command: '/usr/local/bin/ovs-vsctl --no-wait set Open_vSwitch . other_config:dpdk-init=true'
  changed_when: true

- name: set OVS pmd-cpu-mask
  command: '/usr/local/bin/ovs-vsctl --no-wait set Open_vSwitch . other_config:pmd-cpu-mask={{ ovs_dpdk_pmd_mask }}'
  changed_when: true

- name: set OVS dpdk-lcore-mask
  command: '/usr/local/bin/ovs-vsctl --no-wait set Open_vSwitch . other_config:dpdk-lcore-mask={{ ovs_dpdk_lcore_mask }}'
  changed_when: true

- name: WA for bug in DPDK initial device scan - block qat devices
  block:
    - name: get Device ID from PCI address
      shell: "set -o pipefail && lspci -s {{ item.qat_id }} -n |cut -f3 -d' ' |cut -f2 -d':'"
      args:
        executable: /bin/bash
      failed_when: false
      changed_when: false
      register: dev_ids
      with_items: "{{ qat_devices }}"

    - name: get Device ID for VFs from PCI address
      shell: "set -o pipefail && lspci -s {{ item.qat_id }} -vv |grep 'Device ID:' |cut -f4 -d':' |cut -f2 -d' '"
      args:
        executable: /bin/bash
      failed_when: false
      changed_when: false
      register: dev_ids_vfs
      with_items: "{{ qat_devices }}"

    - name: Initialize an empty list for dev_ids
      set_fact:
        dev_ids_list_var: []

    - name: Add dev_ids to list
      set_fact:
        dev_ids_list_var: "{{ dev_ids_list_var + [ item.stdout ] }}"
      with_items: "{{ dev_ids.results }}"

    - name: Add dev_ids_vfs to list
      set_fact:
        dev_ids_list_var: "{{ dev_ids_list_var + [ item.stdout ] }}"
      with_items: "{{ dev_ids_vfs.results }}"
      when: "item.stdout | length>0"

    - name: Print dev_ids_list_var for qat devices
      debug:
        msg: "dev_ids_list_var: {{ dev_ids_list_var }}"

    - name: Make dev_ids list unique
      set_fact:
        dev_ids_list_var: "{{ dev_ids_list_var | unique }}"

    - name: Print unique dev_ids_list_var for qat devices
      debug:
        msg: "unique dev_ids_list_var: {{ dev_ids_list_var }}"

    - name: list QAT devices with vfio-pci driver
      shell: "set -o pipefail && dpdk-devbind.py -s |grep '{{ item }}' |grep 'drv=vfio-pci' |cut -f1 -d' '"
      args:
        executable: /bin/bash
      failed_when: false
      register: qat_dev_sub_list
      changed_when: false
      with_items: "{{ dev_ids_list_var }}"

    - name: Initialize an empty string for qat_dev_list
      set_fact:
        qat_dev_list_var: ""

    - name: Merge qat_dev_sub_lists
      set_fact:
        qat_dev_list_var: "{{ qat_dev_list_var }}{{ item.stdout }}\n"
      with_items: "{{ qat_dev_sub_list.results }}"
      when: "item.stdout | length>0"

    - name: Initialize an empty string for block_list
      set_fact:
        block_list_var: ""

    - name: Prepare info for WA
      set_fact:
        block_list_var: "{{ block_list_var }} {{ ovs_dpdk_extra }}{{ item }}"
      with_items: "{{ qat_dev_list_var.split('\n') }}"
      when:
        - "qat_dev_list_var | length>0"
        - "item | length>0"

    - name: Print block_list_var for qat devices
      debug:
        msg: "block_list_var: {{ block_list_var }}"

    - name: set OVS dpdk-extra - WA for bug in DPDK initial device scan
      command: '/usr/local/bin/ovs-vsctl --no-wait set Open_vSwitch . other_config:dpdk-extra="{{ block_list_var }}"'
      changed_when: true
      when: "block_list_var | length>0"
  when:
    - qat_devices is defined and (qat_devices|length>0)

- name: start OVS vswitchd
  command: /usr/local/share/openvswitch/scripts/ovs-ctl --no-ovsdb-server --db-sock="/usr/local/var/run/openvswitch/db.sock" restart
  environment:
    OVS_RUNDIR: /usr/local/var/run/openvswitch
  changed_when: true

- name: create OVS bridge
  command: /usr/local/bin/ovs-vsctl --may-exist add-br br0 -- set bridge br0 datapath_type=netdev
  changed_when: true
