##
##   Copyright (c) 2020-2022 Intel Corporation.
##
##   Licensed under the Apache License, Version 2.0 (the "License");
##   you may not use this file except in compliance with the License.
##   You may obtain a copy of the License at
##
##       http://www.apache.org/licenses/LICENSE-2.0
##
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.
##
---
- name: create VPP configuration dir if it does not exist
  file:
    path: "{{ vpp_dir }}"
    state: directory
    mode: '0700'
  become: yes

- name: install dependencies on Red Hat
  package:
    name:
      - pygpgme
      - yum-utils
    state: present
  when: ansible_os_family == "RedHat"

- name: add fdio repo gpg key
  apt_key:
    url: "https://packagecloud.io/fdio/{{ vpp_version }}/gpgkey"
    state: present
  when: ansible_os_family == "Debian"

- name: setup vpp repo on RedHat
  template:
    src: fdio.repo
    dest: /etc/yum.repos.d/fdio.repo
    mode: preserve
  when: ansible_os_family == "RedHat"
  register: vpp_sh_rh

- name: capture sysctl configuration
  command: sysctl -n kernel.shmmax vm.max_map_count
  register: original_sysctl
  changed_when: false

- name: calculate intermediate VPP sysctl entries values
  set_fact:
    vpp_orig_shmmax: "{{ original_sysctl.stdout_lines[0] }}"
    vpp_orig_max_map_count: "{{  original_sysctl.stdout_lines[1] }}"
    vpp_calc_shmmax: "{{ (default_hugepage_size == '2M') | ternary(number_of_hugepages_2M*2048*1024, number_of_hugepages_1G*1024*1024*1024) }}"
    vpp_calc_max_map_count: "{{ (default_hugepage_size == '2M') | ternary(number_of_hugepages_2M*3, number_of_hugepages_1G*3) }}"

- name: pick final sysctl entries values
  set_fact:
    vpp_nr_hugepages: "{{ (default_hugepage_size == '2M') | ternary(number_of_hugepages_2M, number_of_hugepages_1G) }}"
    vpp_shmmax: "{{ [vpp_calc_shmmax|int, vpp_orig_shmmax|int] | max }}"
    vpp_max_map_count: "{{ [vpp_orig_max_map_count|int, vpp_calc_max_map_count|int] | max }}"

- name: download packagecloud.io to install VPP packages
  get_url:
    url: "https://packagecloud.io/install/repositories/fdio/{{ vpp_version }}/script.deb.sh"
    dest: "{{ vpp_dir }}"
    mode: 0755

- name: execute VPP bash script
  command: "./script.deb.sh"
  args:
   chdir: "{{ vpp_dir }}"
  changed_when: true

- name: install vpp packages in Red Hat
  package:
    name:
      - vpp
      - vpp-plugins
      - vpp-devel
      - vpp-api-python
      - vpp-api-lua
    state: present
  when: ansible_os_family == "RedHat"

- name: install vpp packages in Debian
  apt:
    update_cache: yes
    name:
      - vpp-plugin-core
      - vpp-plugin-dpdk
      - libvppinfra
      - libvppinfra-dev
      - python3-vpp-api
    state: present
  when: ansible_os_family == "Debian"

- name: write sys config with hugepages and memory settings
  template:
    src: 80-vpp.conf.j2
    dest: /etc/sysctl.d/80-vpp.conf
    mode: preserve

- name: apply sysctl config
  command: sysctl -p --load=/etc/sysctl.d/80-vpp.conf
  changed_when: true

- name: restart vpp service
  systemd:
    name: vpp
    state: restarted
    enabled: yes
