---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: sriov-psp
spec:
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - '*'
  allowedUnsafeSysctls:
  - '*'
  readOnlyRootFilesystem: false
  fsGroup:
    rule: RunAsAny
  hostNetwork: true
  hostIPC: true
  hostPID: true
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - "*"
