##
##   Copyright (c) 2020-2022 Intel Corporation.
##
##   Licensed under the Apache License, Version 2.0 (the "License");
##   you may not use this file except in compliance with the License.
##   You may obtain a copy of the License at
##
##       http://www.apache.org/licenses/LICENSE-2.0
##
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.
##
---
# Install dependencies(ethtool)
- name: install dependencies
  include_role:
    name: install_dependencies

# Check if the selected DDP profile is available in Host
- name: check that the DDP profile exists
  stat:
    path: "{{ ddp_path }}"
  register: stat_result

- name: fail if selected DDP profile not found
  fail:
    msg: "Selected DDP profile {{ ddp_profile }} is not found."
  when: not stat_result.stat.exists

# All looks good; lets install the profile into the NIC
# assuming that the NIC is in fact the PF0
# First, we roll back any existing profile
- name: rolling back any existing DDP profile from the NIC...
  shell: ethtool -f {{ nic }} - 100 2> /dev/null
  failed_when: false
  changed_when: true

# Install new profile into the NIC
- name: installing selected DDP profile into the NIC...
  command: ethtool -f {{ nic }} {{ ddp_profile }} 100
  changed_when: true

- name: template the ddp-i40e systemd service
  template:
    src: ddp_i40e_service.j2
    dest: /lib/systemd/system/ddp-i40e.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: run ddp-i40e service on boot
  systemd:
    daemon_reload: yes
    state: restarted
    name: ddp-i40e
    enabled: yes
