##
##   Copyright (c) 2020-2022 Intel Corporation.
##
##   Licensed under the Apache License, Version 2.0 (the "License");
##   you may not use this file except in compliance with the License.
##   You may obtain a copy of the License at
##
##       http://www.apache.org/licenses/LICENSE-2.0
##
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.
##
---
- name: update network cards
  include: update_network_card.yml
  loop: "{{ dataplane_interfaces }}"
  args:
    bus_info: "{{ item.bus_info }}"
    custom_path_to_profile: "{{ item.ddp_profile | default('') }}"
  when: item.bus_info is regex (".*0$")

- name: show additional information
  debug:
    msg: Skipping {{ item.bus_info }} NIC because it is not 1st physical function of the device.
  when: item.bus_info is not regex (".*0$")
  loop: "{{ dataplane_interfaces }}"

- name: template the ddp-ice systemd service
  template:
    src: ddp_ice_service.j2
    dest: /lib/systemd/system/ddp-ice.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  when: enable_ice_systemd_service | default(false)

- name: run ddp-ice service on boot
  systemd:
    daemon_reload: yes
    state: restarted
    name: ddp-ice
    enabled: yes
  when: enable_ice_systemd_service | default(false)

- name: grep DDP log
  shell: "set -o pipefail && dmesg | grep -i DDP"
  args:
    executable: /bin/bash
  register: grep_result
  changed_when: false

- name: show installed version
  debug:
    msg: "{{ grep_result.stdout_lines }}"
