##
##   Copyright (c) 2020-2022 Intel Corporation.
##
##   Licensed under the Apache License, Version 2.0 (the "License");
##   you may not use this file except in compliance with the License.
##   You may obtain a copy of the License at
##
##       http://www.apache.org/licenses/LICENSE-2.0
##
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.
##
---
minio_application_name: "minio"               # MinIO Main Application Name
minio_operator_namespace: "minio-operator"    # MinIO Operator/Console namespace
minio_tenant_namespace: "minio-tenant"        # MinIO Sample Tenant namespace

minio_operator_release_name: "minio-operator" # MinIO Operator/Console Helm Charts release name
minio_tenant_release_name: "minio-tenant"     # MinIO Tenant Helm Charts release name

minio_storage_worker_key: storage             # MinIO worker key
minio_storage_worker_value: minio             # MinIO worker value

minio_sriov_network_name_prefix: minio-sriov  # MinIO Tenants SriovNetwork name prefix
minio_sriov_network_deviceType: netdevice     # MinIO Tenants SriovNetwork device type
