---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: container-registry
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/registry"
