kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: container-registry
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "manual"
