apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: intel-sgx-aesmd-demo
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: intel-sgx-aesmd-demo
roleRef:
  kind: ClusterRole
  name: intel-sgx-aesmd-demo
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: intel-sgx-aesmd-demo
    namespace: {{ .Release.Namespace }}
