##
##   Copyright (c) 2020-2022 Intel Corporation.
##
##   Licensed under the Apache License, Version 2.0 (the "License");
##   you may not use this file except in compliance with the License.
##   You may obtain a copy of the License at
##
##       http://www.apache.org/licenses/LICENSE-2.0
##
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.
##

# Default values for telemetry-aware-schedulng.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

extenderImage:
  repository: "docker.io/intel/telemetry-aware-scheduling"
  tag: "0.1"
  pullPolicy: IfNotPresent

nameOverride: ""
namespace: default
fullnameOverride: ""
clusterName: "cluster.local"

serviceAccount: {}

service:
  type: ClusterIP
  port: 80

tls:
  enabled: false
#   secretName: extender-secret
#   key: <key>
#   certificate: <secret>

verbosity: 4
