apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gpu-aware-scheduling.fullname" . }}-cluster-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list","watch","update","patch"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: [""]
  resources: ["bindings","pods/binding"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "gpu-aware-scheduling.fullname" . }}-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "gpu-aware-scheduling.fullname" . }}-cluster-role
subjects:
- kind: ServiceAccount
  name: {{ template "gpu-aware-scheduling.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "gpu-aware-scheduling.serviceAccountName" . }}
  labels:
{{ include "gpu-aware-scheduling.labels" . | indent 4 }}
