apiVersion: v1
kind: Service
metadata:
  name: {{ template "gpu-aware-scheduling.serviceName" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "gpu-aware-scheduling.labels" . | indent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "gpu-aware-scheduling.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
